### ISSUE TITLE
Driver won't install

### ISSUE THREAD

**Issue by AlinaNova21** [screeps/driver#1]
I'm trying to do `npm install -g @screeps/driver` since it doesn't seem to be a dependency of screeps/engine, and am receiving the following error:

```
> @screeps/driver@1.0.0 install /home/adam/npm-global/lib/node_modules/@screeps/driver
> node-gyp rebuild -C native

module.js:471
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at bootstrap_node.js:357:29
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/adam/npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-28-generic
gyp ERR! command "/opt/node/bin/node" "/home/adam/npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-C" "native"
gyp ERR! cwd /home/adam/npm-global/lib/node_modules/@screeps/driver/native
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

```

**Comment by artch** [comment]
You don't have to install `@screeps/` modules manually, they are all installed via `screeps` meta-package. There is also no point in installing it globally, since it has no bin command entries.

**Comment by artch** [comment]
`nan` module dependency fixed.
